name: "OnlineJudge"
mode: "dev"
port: 65533
version: "v0.0.1"
start_time: "2023-12-23"
machine_id: 1
auth:
  jwt_expire: 8760
log:
  level: "debug"
  filename: "OnlineJudge.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  protocal: "tcp"
  dbname: "PLOnlineJudge"
  max_open_conns: 200
  max_idle_conns: 50
